name: 'Authenticate via OIDC'

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:

  authenticate:
    environment: Dev
    
    name: 'Azure OIDC Authentication'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Azure OIDC Authentication'
        uses: Azure/login@v1
        with:
          allow-no-subscriptions: true
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}